name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0-190.1.beta

dependencies:
  args: ^2.4.0
  http: ^1.2.1
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_helmet: ^2.2.1
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.0
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
