name: static_server
description: Web server to test two site flutter embedding in web page
version: 1.0.0
repository: https://github.com/freemansoft/flutter-embedded

environment:
  sdk: ^3.3.0

dependencies:
  args: ^2.4.0
  http: ^1.2.1
  shelf: ^1.4.0
  shelf_helmet: ^2.2.1
  shelf_proxy: ^1.0.4
  shelf_router: ^1.1.0
  shelf_static: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
